NodeMachine/codebase

.gitignore, client/app.js, client/components/navbar.js, client/components/userProblemsList.js, client/components/userProfile.js, client/routes.js, package-lock.json, package.json, public/index.html, webpack.config.js
=> Profile page

server/api/index.js, server/api/userRoutes.js, server/auth/index.js, server/db/queryFunctions/index.js, server/db/queryFunctions/userQueryFunctions.js
=> feat: user routes added

client/components/aceCode.js, client/components/resultWindow.js, client/components/singleProblem.js, server/api/solution.js, server/db/queryFunctions/problemQueryFunctions.js
=> Problem vertical slice

client/components/auth-form.js, client/components/userProblemsList.js, client/components/userProfile.js, client/store/user.js, package-lock.json, server/api/userRoutes.js, server/db/queryFunctions/userQueryFunctions.js
=> User redux

server/api/userRoutes.js
=> Protect routes

client/components/companyHome.js, client/components/companyProfile.js, client/components/index.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, server/api/userRoutes.js, server/db/queryFunctions/userQueryFunctions.js
=> feat: companyhome page can list all users

client/components/singleProblem.js
=> style: updated Ace Editor theme

client/components/problemsList.js, client/components/singleProblem.js, client/store/problems.js
=> Updated user problems

client/components/resultWindow.js, client/components/singleProblem.js, server/api/solution.js
=> Problem output

client/components/auth-form.js, client/store/user.js, server/api/userRoutes.js
=> Password fix

client/components/auth-form.js, client/components/navbar.js
=> feat: the site name is now a link to the '/' route.

client/components/resultWindow.js, client/components/singleProblem.js, server/api/solution.js
=> Result window

client/components/navbar.js, client/components/userProblemsList.js, client/components/userProfile.js, client/store/user.js
=> Profile page hookup

client/app.js, client/components/mainPage.js, client/components/navbar.js, client/components/problemDescription.js, client/components/problemsList.js, client/components/resultWindow.js, client/components/singleProblem.js, client/components/userProfile.js, public/index.html, public/style.css
=> Single problem style

client/app.js, client/components/mainPage.js, client/components/navbar.js, client/components/problemDescription.js, client/components/problemsList.js, client/components/resultWindow.js, client/components/singleProblem.js, client/components/userInformation.js, client/components/userProblemsList.js, client/components/userProfile.js, client/store/user.js, public/index.html, public/style.css
=> Fix: a user's code now loads when they click through from their profile page.

client/components/userProblemsList.js
=> fix: a user's code now loads when they click-through from their profile.

client/components/auth-form.js, server/api/userRoutes.js
=> fix: score now updates

client/components/auth-form.css, client/components/auth-form.js
=> feat: form now has style

client/components/navbar.css, client/components/navbar.js
=> style: navbar cleanup.

client/components/problemList.css
=> style: aligned column titles;

client/components/auth-form.css
=> fix: fixed login page style

server/api/userRoutes.js, server/api/users.spec.js
=> fix: user routes are now passing tests

client/components/mainPage.css, client/components/mainPage.js, client/components/navbar.css, client/components/navbar.js, client/components/problemList.css, client/components/problemsList.js, client/components/singleProblem.css, public/style.css
=> Landing page

client/components/userProfile.css
=> style: profile page displays below navbar

client/components/auth-form.css, client/store/user.spec.js, docker-compose.yml, heroku.yml, server/api/solution.js
---
**Not sure how my deployment commits got over here. Anyone know how to fix it?**
=> User redux tests

client/store/user.js, server/api/userRoutes.js
=> fix: fixed bug from timeout

package.json, server/api/solution.js, server/api/solution.spec.js
=> tests: the solution API handles user code, and errors, correctly

client/components/userAnalytics.css, client/components/userAnalytics.js, client/components/userAnalytics.js.rej, client/components/userProfile.css, client/components/userProfile.js, package-lock.json, package.json, public/index.html
=> User analytics

client/components/singleProblem.js
=> fix: problems now load the user's last solution on refresh.

client/components/resultWindow.js, client/components/singleProblem.js, server/api/solution.js
=> fix: solution now tests for output type

client/components/companyProblemForm.js
=> feat: unhooked up company problem form

client/store/problems.js, client/store/problems.spec.js, server/api/problems.spec.js, server/api/solution.js
=> test: tests for the problems store

client/components/problemList.css, client/components/userProblemsList.js, client/components/userProfile.css
=> Submit button

client/components/companyProblemsList.js
=> feat: unhooked company problems list component built

client/components/companySavedUsersList.js
=> feat: unhooked up company saved users componenet

client/store/companyProblems.js
=> feat: added custom problems thunks

client/store/companyUsers.js, server/api/companyUsers.js, server/api/index.js, server/db/queryFunctions/companyQueryFunctions.js
=> feat: added a 'delete user' queery function.

client/store/companyProblems.js, server/api/companyCopy.js, server/api/userRoutes.js, server/db/queryFunctions/companyQueryFunctions.js
=> feat: custom problem query functions added

client/components/companyInformation.js, client/components/companyProblemForm.js, client/components/companyProblemsList.js, client/components/companyProfile.js, client/components/companySavedUsersList.js, client/components/userInformation.js, client/store/company.js, client/store/user.js, server/api/company.js, server/api/userRoutes.js, server/db/queryFunctions/companyQueryFunctions.js
=> feat: Company profile now hooked up

client/app.js, client/components/companyNavbar.js, client/routes.js, client/store/company.js, server/auth/index.js
=> Company navbar

client/components/companyInformation.js, client/components/companyNavbar.js, client/components/companyProfile.js, client/routes.js, server/api/company.js, server/db/queryFunctions/companyQueryFunctions.js
=> Company profile

client/components/companyProblemForm.js, client/store/company.js, server/api/company.js, server/db/queryFunctions/companyQueryFunctions.js
=> fix: company can now submit problems

client/app.js, client/components/companyHome.js, client/components/companyProfile.js, client/components/companySavedUsersList.js, client/components/developerListItem.js, client/routes.js, client/store/company.js, server/api/company.js, server/api/userRoutes.js, server/db/queryFunctions/companyQueryFunctions.js
=> Company developer list

client/components/auth-form.js, client/components/companyProblemForm.js, client/components/companyProfile.js, server/api/company.js
=> feat: redirects users and companies to profile page

client/components/singleProblem.css, client/components/singleProblem.js
=> feat: user has directions on single problem page

client/components/companyProblemsList.js, client/components/companyProfile.js, server/api/company.js, server/db/queryFunctions/companyQueryFunctions.js
=> Company problem list

client/components/singleProblem.css, client/components/singleProblem.js
=> feat: reset button greys out when code is being run

client/components/auth-form.js, client/store/user.js
=> fix: login error message disappears when user starts typing in the form

server/api/userRoutes.js
=> fix: changed date rule for profile pics

client/components/companyHome.css, client/components/companyHome.js, client/components/developerListItem.js, server/api/company.js
=> bug fix: newly signed up users can now view all developers.

client/components/problemList.css, client/components/problemsListPage.js
=> Problemlist style

client/components/companyProfile.js, client/components/companySavedUsersList.js, server/api/company.js, server/db/queryFunctions/companyQueryFunctions.js
=> fix: company can now remove user

client/components/companyHome.css, client/components/companyHome.js, client/components/developerListItem.js, client/components/singleProblem.css, public/style.css
=> style: developer list styled

client/components/companyProblemForm.js, client/components/companyProfile.css, client/components/companyProfile.js, client/components/companySavedUsersList.js, server/api/company.js
=> Companyprofile style

client/components/auth-form.css, client/components/auth-form.js
=> css: login/sign up form

client/components/auth-form.js, server/auth/index.js
=> fix: header error removed

client/components/problemList.css, client/components/problemsListPage.js
=> style: added styling to the filter items

server/api/company.js
=> fix: console logs removed

server/api/solution.js
=> fix: fixed bug where unknown variable crashes app

client/components/mainPage.css
=> Hero image

client/components/companyHome.css, client/components/developerListItem.js, server/api/solution.js, server/db/queryFunctions/userQueryFunctions.js
=> fix: added delete button to developer list

client/components/problemList.css, client/components/problemListItem.js
=> Problem list style links

client/components/companyProblemsList.js, client/components/companySavedUsersList.js
=> fix: now can see user's solution code on profile page

client/components/navbar.css, client/components/navbar.js
=> style: updated logo

client/components/companyHome.css, client/components/developerListItem.js
=> style: developer list items aligned

client/components/auth-form.css, client/components/auth-form.js
=> style: styling for login/signup

client/components/companyProblemForm.js, server/api/solution.js
=> fix: problem.test to problem.tests when company uploads problem

client/components/companyNavbar.js
=> style: updated business navbar

client/components/companyProblemForm.js
=> fix: add quotes to form

client/components/aceCode.js, client/components/companySavedUsersList.js, client/components/user-home.js, server/api/solution.js
=> chore: more clean up

client/components/singleProblem.css, client/components/singleProblem.js
=> style: fixed alignment on single problem page
